#service port
server:
  port: 8080

#register with eureka
eureka:
  client:
    register-with-eureka: false

#expose service's routes
spring:
  cloud:
    gateway:
      mvc:
        routesMap:
          userauth-service:
            uri: http://localhost:8090
            predicates:
              - Path=/api/user/**
              - Path=/api/auth/**
              - Path=/swagger-ui/**
