#service port
server:
  port: 8080

#register with eureka
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

#expose service's routes
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: userauth-service
          uri: lb://userauth-service
          predicates:
            - Path=/api/user/**
            - Path=/api/auth/**
            - Path=/swagger-ui/**
