#service port
server:
  port: 8080

#register with eureka
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

#expose service's routes
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: userauth-service
          uri: 'http://localhost:8090'
          predicates:
            - Path=/api/user/**
            - Path=/api/auth/**
            - Path=/swagger-ui/**
