#service port
server:
  port: 8080

#register with eureka
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

#expose service's routes
spring:
  cloud:
    gateway:
      #register with eureka
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      #filters that pass the token to the protected resources (resource servers)
      default-filters:
        - TokenRelay
      routes:
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/api/user/**
            - Path=/api/auth/**
            - Path=/swagger-ui/**
        - id: rooms-service
          uri: lb://rooms-service
          predicates:
            - Path=/api/room/**
            - Path=/swagger-ui/**
          filters:
            - RemoveRequestHeader=Cookie

#logging requests
logging:
  level:
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: TRACE

#enable & expose actuator endpoints (for admin-server)
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
