#service port
server:
  port: 8091

#register with eureka
eureka:
  client:
    service-url:
      default-zone: http://host.docker.internal:8761/eureka
  instance:
    hostname: localhost

#enable & expose actuator endpoints (for admin-server)
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

#Keycloak OAuth2 Configuration
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://host.docker.internal:9090/realms/Flexidorms

#circuit breaker configuration
resilience4j.circuitbreaker:
  instances:
    account-cb:
      registerHealthIndicator: true
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 5
      waitDurationInOpenState: 5s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
