spring:
  application:
    name: gateway-service
  config:
    import:
      - configserver:http://localhost:8888
      - env.properties

  #oauth2 configuration for keycloak
  security:
    oauth2:
      client:
        provider:
          keycloak:
            user-name-attribute: preferred_username
            issuer-uri: http://localhost:9090/realms/Flexidorms
        registration:
          flexidorms-client:
            client-id: flexidorms-client
            client-secret: ${CLIENT_SECRET}
            provider: keycloak
            scope: openid
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
