#banner -> ogre
spring:
  application:
    name: registry-service
  #importa la configuracion de un servidor
  config:
    import: optional:configserver:http://localhost:8888

server:
  port: 8761

#Eureka Server Configuration
eureka:
  instance:
    hostname: localhost
  client:
    #que no se registre a si mismo
    register-with-eureka: false
    fetch-registry: false
    #url del servidor de eureka
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/